"""
Django settings for ohca project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from .suppl import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv('SERVER_DEBUG', 'false').lower() == 'true'
SQLITE = os.getenv('SERVER_LOCAL_DB', 'false').lower() == 'true'

ALLOWED_HOSTS = list(map(str.strip, os.getenv('ALLOWED_HOSTS', '*').split(',')))

SECRET_KEY = os.getenv('SECRET_KEY')

databases = { 'default': dict() }

if SQLITE:
    databases['default']['ENGINE'] = 'django.db.backends.sqlite3'
    databases['default']['NAME'] = os.getenv('DB_PATH', '.') + '/ohca.db'
else:
    databases['default']['ENGINE'] = engine[os.getenv('DATABASE')]
    databases['default']['NAME'] = os.getenv('DATABASE_NAME')
    databases['default']['USER'] = os.getenv('DATABASE_USER')
    databases['default']['PASSWORD'] = os.getenv('DATABASE_PASS')
    databases['default']['HOST'] = os.getenv('DATABASE_HOST', 'localhost')
    databases['default']['PORT'] = int(os.getenv('DATABASE_PORT', db_port[os.getenv('DATABASE')]))
    databases['default']['OPTIONS'] = { "init_command":"SET foreign_key_checks = 0;", } #TODO

DATABASES = databases

# Application definition

INSTALLED_APPS = [
    'ohca',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ohca.middleware.NoClientCaching',
]

ROOT_URLCONF = 'ohca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ohca.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Ljubljana'

USE_I18N = True

USE_TZ = True

USE_L10N = False

DATE_FORMAT = 'd m y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

cacheConfig = dict()
if DEBUG:
    cacheConfig = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': 60
        }
    }
else:
    cacheConfig = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': 'memcached:11211',
            'TIMEOUT': None
        }
    }

CACHES = cacheConfig

CRISPY_TEMPLATE_PACK = 'bootstrap4'
